# jwt configuration
jwt:
  signing-key: 'qmPlus'
  buffer-time: 86400
  expires-time: 604800

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GF-VUE-ADMIN]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# gorm configuration
gorm:
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  log-zap: false
  log-mode: "info"
  auto-migrate: false
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
  conn-max-idle-time: 24h
  dsn:
    sources:
      - host: '127.0.0.1'
        port: '5432'
        db-name: 'gva'
        username: 'root'
        password: 'gdkid,,..'
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
    replicas:
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# casbin configuration
casbin:
  model-path: './public/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 Oss函数配置
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  verification: false

# auto-code configuration
auto-code:
  root: ''
  server:
    root: ''
    api: '/app/api/example'
    boot: '/boot'
    router: '/boot'
    model: '/app/model/example'
    request: '/app/model/example/request'
    service: '/app/service/example'
  web:
    root: '/web/src'
    api: '/api'
    flow: '/view'
    form: '/view'
    table: '/view'
  restart: true